package com.pk.cwierkacz.ws.client;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebFault( name = "userNotExistFault", targetNamespace = "http://pk.edu.pl/ias/types" )
public class UserNotExistFault extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private final pl.edu.pk.ias.types.UserNotExistFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UserNotExistFault( String message, pl.edu.pk.ias.types.UserNotExistFault faultInfo ) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UserNotExistFault( String message, pl.edu.pk.ias.types.UserNotExistFault faultInfo, Throwable cause ) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return returns fault bean: pl.edu.pk.ias.types.UserNotExistFault
     */
    public pl.edu.pk.ias.types.UserNotExistFault getFaultInfo( ) {
        return faultInfo;
    }

}
