
package pl.edu.pk.ias.socialserviceintegration;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "invalidLoginOrPasswordFault", targetNamespace = "http://pk.edu.pl/ias/types")
public class InvalidLoginOrPasswordFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private pl.edu.pk.ias.types.InvalidLoginOrPasswordFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidLoginOrPasswordFault(String message, pl.edu.pk.ias.types.InvalidLoginOrPasswordFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidLoginOrPasswordFault(String message, pl.edu.pk.ias.types.InvalidLoginOrPasswordFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pl.edu.pk.ias.types.InvalidLoginOrPasswordFault
     */
    public pl.edu.pk.ias.types.InvalidLoginOrPasswordFault getFaultInfo() {
        return faultInfo;
    }

}
