
package pl.edu.pk.ias.socialserviceintegration;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "serviceUnavailableFault", targetNamespace = "http://pk.edu.pl/ias/types")
public class ServiceUnavailableFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private pl.edu.pk.ias.types.ServiceUnavailableFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceUnavailableFault(String message, pl.edu.pk.ias.types.ServiceUnavailableFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceUnavailableFault(String message, pl.edu.pk.ias.types.ServiceUnavailableFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pl.edu.pk.ias.types.ServiceUnavailableFault
     */
    public pl.edu.pk.ias.types.ServiceUnavailableFault getFaultInfo() {
        return faultInfo;
    }

}
